# Generated by Django 2.2 on 2021-09-12 07:17

import ckeditor.fields
import competence.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competence', '0003_auto_20210912_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockCompetenceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=competence.models.upload_location)),
                ('date_published', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='block', to='competence.CompetenceModel')),
            ],
            options={
                'verbose_name': 'Competence blocks',
                'verbose_name_plural': 'Competence blocks',
                'ordering': ['date_published'],
            },
        ),
    ]
