# Generated by Django 2.2 on 2021-09-12 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competence', '0006_auto_20210912_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockcompetencemodel',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='competence.CompetenceModel'),
        ),
    ]
