# Generated by Django 2.2 on 2021-04-18 11:02

from django.db import migrations, models
import infopages.models


class Migration(migrations.Migration):

    dependencies = [
        ('infopages', '0002_industriesmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsmodel',
            old_name='image',
            new_name='little_image',
        ),
        migrations.AddField(
            model_name='newsmodel',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to=infopages.models.upload_location),
        ),
    ]
