# Generated by Django 2.2 on 2021-04-20 17:54

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infopages', '0004_infopagemodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infopagemodel',
            options={'ordering': ['-date_published'], 'verbose_name': 'Info page', 'verbose_name_plural': 'Info pages'},
        ),
        migrations.AddField(
            model_name='infopagemodel',
            name='pre_info',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
