# Generated by Django 2.2 on 2021-07-31 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infopages', '0005_auto_20210420_2254'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsmodel',
            options={'ordering': ['-date_published'], 'verbose_name': 'News and Analytics', 'verbose_name_plural': 'News and Analytics'},
        ),
    ]
