# Generated by Django 2.2 on 2021-04-20 08:57

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('entrepreneur', '0002_businessmodel_filtermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessmodel',
            name='price',
            field=djmoney.models.fields.MoneyField(decimal_places=0, default_currency='USD', max_digits=14),
        ),
    ]
