# Generated by Django 2.2 on 2021-07-27 08:31

import ckeditor.fields
from django.db import migrations, models
import wedo.models


class Migration(migrations.Migration):

    dependencies = [
        ('wedo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpportunitiesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=wedo.models.upload_location)),
                ('date_published', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'You do not see',
                'ordering': ['-date_published'],
            },
        ),
        migrations.CreateModel(
            name='PhotoBankModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=wedo.models.upload_location)),
                ('date_published', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'Photo bank',
                'ordering': ['-date_published'],
            },
        ),
        migrations.AlterModelOptions(
            name='informationpagesmodel',
            options={'ordering': ['-date_published'], 'verbose_name': 'What are we doing?', 'verbose_name_plural': 'What are we doing?'},
        ),
    ]
