# Generated by Django 2.2 on 2021-07-31 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wedo', '0002_auto_20210727_1331'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opportunitiesmodel',
            options={'ordering': ['-date_published'], 'verbose_name': 'Business Opportunities'},
        ),
    ]
