# Generated by Django 2.2 on 2021-07-31 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedo', '0004_newsmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='category',
            field=models.CharField(choices=[('News and Analytics', 'News and Analytics'), ('Interesting facts', 'Interesting facts'), ('Data and Statistics', 'Data and Statistics'), ('Publications', 'Publications')], default='News and Analytics', max_length=50),
        ),
    ]
