# Generated by Django 2.2 on 2021-07-31 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asia', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='centralasiapagesmodel',
            options={'ordering': ['date_published'], 'verbose_name': 'Central Asia', 'verbose_name_plural': 'Central Asia'},
        ),
    ]
