# Generated by Django 2.2 on 2021-07-31 16:13

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asia', '0002_auto_20210731_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='centralasiapagesmodel',
            name='body_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='centralasiapagesmodel',
            name='body_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='centralasiapagesmodel',
            name='body_uz',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='centralasiapagesmodel',
            name='title_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='centralasiapagesmodel',
            name='title_ru',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='centralasiapagesmodel',
            name='title_uz',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
