# Generated by Django 2.2 on 2021-07-31 17:51

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asia', '0003_auto_20210731_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='centralasiapagesmodel',
            name='body_ar',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='centralasiapagesmodel',
            name='body_de',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='centralasiapagesmodel',
            name='body_ja',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='centralasiapagesmodel',
            name='body_ko',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='centralasiapagesmodel',
            name='body_zh_cn',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='centralasiapagesmodel',
            name='title_ar',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='centralasiapagesmodel',
            name='title_de',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='centralasiapagesmodel',
            name='title_ja',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='centralasiapagesmodel',
            name='title_ko',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='centralasiapagesmodel',
            name='title_zh_cn',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
